=== olawale24/myserver/opt/tectia/share/auxdata/common/ssh-secsh-auth-form-1.dtd
<!--  									-->
<!--  									-->
<!-- secsh-auth-form.dtd						-->
<!--  									-->
<!-- Author: Timo J. Rinne <tri@ssh.com>				-->
<!--  									-->
<!-- Copyright (c) 2016 SSH Communications Security Corporation.	-->
<!-- This software is protected by international copyright laws.	-->
<!-- All rights reserved.						-->
<!--  									-->
<!-- Document type description for SecSh user authentication		-->
<!-- forms XML format.  This should be a subset of xforms.		-->
<!--									-->
<!--									-->

<!--									-->
<!-- Attribute lang is a language tag according to RFC3066		-->
<!--									-->
<!ELEMENT label		(#PCDATA)>
<!ATTLIST label		lang		CDATA		#IMPLIED>

<!--									-->
<!-- Attribute lang is a language tag according to RFC3066		-->
<!--									-->
<!ELEMENT hint		(#PCDATA)>
<!ATTLIST hint		lang		CDATA		#IMPLIED>

<!--									-->
<!--									-->
<!ELEMENT value		(#PCDATA)>

<!--									-->
<!--									-->
<!ELEMENT send		EMPTY>
<!ATTLIST send		submission	NMTOKEN		#REQUIRED>

<!--									-->
<!--									-->
<!ELEMENT input		(label,
                         hint?,
			 value?,
			 send?)>
<!ATTLIST input		ref		ID		#REQUIRED
			maxinputlength	CDATA		#IMPLIED>

<!--									-->
<!--									-->
<!ELEMENT secret	(label,
                         hint?,
			 value?,
			 send?)>
<!ATTLIST secret	ref		ID		#REQUIRED
			maxinputlength	CDATA		#IMPLIED>

<!--									-->
<!--									-->
<!ELEMENT output	(label,
                         hint?,
			 send?)>
<!ATTLIST output	ref		NMTOKEN		#IMPLIED>

<!--									-->
<!--									-->
<!ELEMENT textarea	(label,
                         hint?,
			 value?,
			 send?)>
<!ATTLIST textarea	ref		ID		#REQUIRED
			maxinputlength	CDATA		#IMPLIED>

<!ELEMENT range		(label,
			 hint?,
			 value?,
			 send?)>
<!ATTLIST range		ref		ID		#REQUIRED
			start		CDATA		#REQUIRED
			end		CDATA		#REQUIRED
			step		CDATA		#REQUIRED>

<!--									-->
<!--									-->
<!ELEMENT trigger	(label,
			 hint?,
			 send?)>
<!ATTLIST trigger	ref		ID		#REQUIRED>

<!--									-->
<!--									-->
<!ELEMENT submit	(label,
			 hint?)>
<!ATTLIST submit	ref		ID		#REQUIRED>

<!--									-->
<!--									-->
<!ELEMENT item		(label,
			 hint?,
			 value)>

<!--									-->
<!--									-->
<!ELEMENT select1	(label,
			 hint?,
			 item+,
			 value?,
			 send?)>
<!ATTLIST select1	ref		ID		#REQUIRED>

<!--									-->
<!--									-->
<!ELEMENT select	(label,
			 hint?,
			 item+,
			 value*,
			 send?)>
<!ATTLIST select	ref		ID		#REQUIRED>

<!--									-->
<!--									-->
<!ELEMENT group		(label,
			 hint?,
			 label*,
    ((input|secret|textarea|submit|trigger|range|select|select1|output|group)+,
			  label*)+)>
<!ATTLIST group		id 		NMTOKEN		#IMPLIED>

<!--									-->
<!--									-->
<!ELEMENT form		(label,
			 hint?,
			 (label|input|secret|textarea|submit|trigger|
			  range|select|select1|output|group)+)>
<!ATTLIST form		id		NMTOKEN		#REQUIRED
			focus		NMTOKEN		#IMPLIED>

=== olawale24/myserver/opt/tectia/share/auxdata/common/af-store-passphrase.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE form PUBLIC "ssh-secsh-auth-form-1.dtd" "ssh-secsh-auth-form-1.dtd">
<form id="store-passphrase">
<label></label>
<!-- BEGIN BLOCK: OPEN STORE -->
<label>Please provide passphrase to open %%%STORENAME%%%.</label>
<!-- END BLOCK: OPEN STORE -->
<!-- BEGIN BLOCK: NEW STORE PASSPHRASE -->
<label>Please input new passphrase for %%%STORENAME%%%.</label>
<!-- END BLOCK: NEW STORE PASSPHRASE -->
<secret ref="passphrase">
<label>Passphrase</label>
%%%SENDSUBMISSION%%%
</secret>
<!-- BEGIN BLOCK: NEW PASSPHRASE -->
<secret ref="passphrase-again">
<label>Passphrase again</label>
<send submission="ok" />
</secret>
<!-- END BLOCK: NEW PASSPHRASE -->
<submit ref="ok" >
<label>OK</label>
</submit>
<submit ref="cancel" >
<label>Cancel</label>
</submit>
</form>

=== olawale24/myserver/opt/tectia/share/auxdata/common/af-username.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE form PUBLIC "ssh-secsh-auth-form-1.dtd" "ssh-secsh-auth-form-1.dtd">
<form id="user">
<label></label>
<label>Host: %%%SERVERHOST-SERVERPORT%%%</label>
<input ref="user">
<label>User</label>
<send submission="ok" />
</input>
<submit ref="ok" >
<label>OK</label>
</submit>
<submit ref="cancel" >
<label>Cancel</label>
</submit>
</form>

=== olawale24/myserver/opt/tectia/share/auxdata/common/af-password.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE form PUBLIC "ssh-secsh-auth-form-1.dtd" "ssh-secsh-auth-form-1.dtd">
<form id="password">
<label></label>
<secret ref="password">
<label>%%%USERNAME%%%@%%%SERVERHOST-SERVERPORT%%%'s password</label>
<send submission="ok" />
</secret>
<submit ref="ok" >
<label>OK</label>
</submit>
<submit ref="cancel" >
<label>Cancel</label>
</submit>
</form>
