=== olawale24/myserver/opt/tectia/share/auxdata/common/ssh-secsh-auth-form-1.dtd
<!--  									-->
<!--  									-->
<!-- secsh-auth-form.dtd						-->
<!--  									-->
<!-- Author: Timo J. Rinne <tri@ssh.com>				-->
<!--  									-->
<!-- Copyright (c) 2016 SSH Communications Security Corporation.	-->
<!-- This software is protected by international copyright laws.	-->
<!-- All rights reserved.						-->
<!--  									-->
<!-- Document type description for SecSh user authentication		-->
<!-- forms XML format.  This should be a subset of xforms.		-->
<!--									-->
<!--									-->

<!--									-->
<!-- Attribute lang is a language tag according to RFC3066		-->
<!--									-->
<!ELEMENT label		(#PCDATA)>
<!ATTLIST label		lang		CDATA		#IMPLIED>

<!--									-->
<!-- Attribute lang is a language tag according to RFC3066		-->
<!--									-->
<!ELEMENT hint		(#PCDATA)>
<!ATTLIST hint		lang		CDATA		#IMPLIED>

<!--									-->
<!--									-->
<!ELEMENT value		(#PCDATA)>

<!--									-->
<!--									-->
<!ELEMENT send		EMPTY>
<!ATTLIST send		submission	NMTOKEN		#REQUIRED>

<!--									-->
<!--									-->
<!ELEMENT input		(label,
                         hint?,
			 value?,
			 send?)>
<!ATTLIST input		ref		ID		#REQUIRED
			maxinputlength	CDATA		#IMPLIED>

<!--									-->
<!--									-->
<!ELEMENT secret	(label,
                         hint?,
			 value?,
			 send?)>
<!ATTLIST secret	ref		ID		#REQUIRED
			maxinputlength	CDATA		#IMPLIED>

<!--									-->
<!--									-->
<!ELEMENT output	(label,
                         hint?,
			 send?)>
<!ATTLIST output	ref		NMTOKEN		#IMPLIED>

<!--									-->
<!--									-->
<!ELEMENT textarea	(label,
                         hint?,
			 value?,
			 send?)>
<!ATTLIST textarea	ref		ID		#REQUIRED
			maxinputlength	CDATA		#IMPLIED>

<!ELEMENT range		(label,
			 hint?,
			 value?,
			 send?)>
<!ATTLIST range		ref		ID		#REQUIRED
			start		CDATA		#REQUIRED
			end		CDATA		#REQUIRED
			step		CDATA		#REQUIRED>

<!--									-->
<!--									-->
<!ELEMENT trigger	(label,
			 hint?,
			 send?)>
<!ATTLIST trigger	ref		ID		#REQUIRED>

<!--									-->
<!--									-->
<!ELEMENT submit	(label,
			 hint?)>
<!ATTLIST submit	ref		ID		#REQUIRED>

<!--									-->
<!--									-->
<!ELEMENT item		(label,
			 hint?,
			 value)>

<!--									-->
<!--									-->
<!ELEMENT select1	(label,
			 hint?,
			 item+,
			 value?,
			 send?)>
<!ATTLIST select1	ref		ID		#REQUIRED>

<!--									-->
<!--									-->
<!ELEMENT select	(label,
			 hint?,
			 item+,
			 value*,
			 send?)>
<!ATTLIST select	ref		ID		#REQUIRED>

<!--									-->
<!--									-->
<!ELEMENT group		(label,
			 hint?,
			 label*,
    ((input|secret|textarea|submit|trigger|range|select|select1|output|group)+,
			  label*)+)>
<!ATTLIST group		id 		NMTOKEN		#IMPLIED>

<!--									-->
<!--									-->
<!ELEMENT form		(label,
			 hint?,
			 (label|input|secret|textarea|submit|trigger|
			  range|select|select1|output|group)+)>
<!ATTLIST form		id		NMTOKEN		#REQUIRED
			focus		NMTOKEN		#IMPLIED>

=== olawale24/myserver/opt/tectia/share/auxdata/common/af-hostkeycheck-gui.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE form PUBLIC "ssh-secsh-auth-form-1.dtd" "ssh-secsh-auth-form-1.dtd">
<form id="hostkeycheck">
<label/>
<label>Host key for the host "%%%SERVERHOST-SERVERPORT%%%" not found from database.</label>
<label>
The fingerprint of the host public key is:
Babble: "%%%HOSTKEYFINGERPRINT%%%"
RFC4716: "%%%HOSTKEYFINGERPRINT_RFC4716%%%"
</label>
<select1 ref="hostkeycheck">
<label>Please select how you want to proceed.</label>
<item>
  <label>Cancel the connection.</label>
  <value>cancel</value>
</item>
<item>
  <label>Proceed with the connection but do not save the key.</label>
  <value>once</value>
</item>
<item>
  <label>Proceed with the connection and save the key for future use.</label>
  <value>save</value>
</item>
<value>cancel</value>
</select1>
<submit ref="ok">
<label>OK</label>
</submit>
</form>

=== olawale24/myserver/opt/tectia/share/auxdata/common/af-hostname.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE form PUBLIC "ssh-secsh-auth-form-1.dtd" "ssh-secsh-auth-form-1.dtd">
<form id="host">
<label></label>
<input ref="host">
<label>Host</label>
<send submission="ok" />
</input>
<submit ref="ok" >
<label>OK</label>
</submit>
<submit ref="cancel" >
<label>Cancel</label>
</submit>
</form>

=== olawale24/myserver/opt/tectia/share/auxdata/common/af-new-password.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE form PUBLIC "ssh-secsh-auth-form-1.dtd" "ssh-secsh-auth-form-1.dtd">
<form id="new-password">
<label/>
<label>%%%PROMPT%%%</label>
<label>Host: %%%SERVERHOST-SERVERPORT%%%</label>
<label>User: %%%USERNAME%%%</label>
<secret ref="password">
<label>New password</label>
</secret>
<secret ref="check">
<label>Again</label>
<send submission="ok" />
</secret>
<submit ref="ok" >
<label>OK</label>
</submit>
<submit ref="cancel" >
<label>Cancel</label>
</submit>
</form>

=== olawale24/myserver/opt/tectia/share/auxdata/common/af-endpointnotmatch.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE form PUBLIC "ssh-secsh-auth-form-1.dtd" "ssh-secsh-auth-form-1.dtd">
<form id="endpointcheck">
<label/>
<label>End point identity for host "%%%SERVERHOST%%%" does not match.</label>
<label> </label>
<label>Certificate:</label>
%%%CERTDESCRIPTION%%%
<label> </label>
<select1 ref="endpointcheck">
<label>Please select how you want to proceed.</label>
<item>
  <label>Cancel the connection.</label>
  <value>cancel</value>
</item>
<item>
  <label>Accept host identity.</label>
  <value>accept</value>
</item>
<value>cancel</value>
</select1>
</form>

=== olawale24/myserver/opt/tectia/share/auxdata/common/af-certificateinfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE form PUBLIC "ssh-secsh-auth-form-1.dtd" "ssh-secsh-auth-form-1.dtd">
<form id="certificateinfo">
<label/>
<label> </label>
<label>Certificate:</label>
%%%CERTDESCRIPTION%%%
<label> </label>
<select1 ref="certificateinfo">
<label>Please select how you want to proceed.</label>
<item>
  <label>Back to accept dialog.</label>
  <value>back</value>
</item>
<item>
  <label>Cancel connection.</label>
  <value>cancel</value>
</item>
<value>back</value>
</select1>
</form>

=== olawale24/myserver/opt/tectia/share/auxdata/common/af-publickey-selection.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE form PUBLIC "ssh-secsh-auth-form-1.dtd"
  "ssh-secsh-auth-form-1.dtd"[
  <!ENTITY rejected "[rejected]">
  <!ENTITY failed "[failed]">
]>
<form id="certselect">
<label/>
<label>
Client authentication is required. Please select the key to 
authenticate yourself with.</label>
<label>
Server host is %%%SERVERHOST%%%:%%%SERVERPORT%%%</label>
<!-- BEGIN BLOCK: FAILED-CERTIFICATE -->
<label>
Failed to authenticate with certificate %%%ID%%%:
         Subject: %%%SUBJECTNAME%%%
         Serial: %%%SERIALNUMBER%%%
         %%%ERRORMESSAGE%%%
</label>
<!-- END BLOCK: FAILED-CERTIFICATE -->
<!-- BEGIN BLOCK: FAILED-PUBLICKEY -->
<label>
Failed to authenticate with public key %%%ID%%%:
         Label: %%%LABEL%%%
         Key path: %%%PATH%%%
         %%%ERRORMESSAGE%%%
</label>
<!-- END BLOCK: FAILED-PUBLICKEY -->
<!-- BEGIN BLOCK: FAILED-NO-SUCH-KEY -->
<label>
Failed to authenticate: key %%%ID%%% not available.
</label>
<!-- END BLOCK: FAILED-NO-SUCH-KEY -->
<select1 ref="client-publickey">
<label>Please select one key.</label>
<!-- BEGIN BLOCK: CERTIFICATE -->
<item>
  <label> Subject: %%%SUBJECTNAME%%% %%%STATUS%%%
 Issuer: %%%ISSUERNAME%%%
 Serial: %%%SERIALNUMBER%%%
 Valid until: %%%VALID-NOT-AFTER%%%</label>
 <!--
   %%%ALGORITHM%%% [hash #%%%HASH%%%]
   File name: %%%FILENAME%%%
   Key path: %%%KEYPATH%%%
 -->
  <value>%%%ID%%%</value>
</item>
<!-- END BLOCK: CERTIFICATE -->
<!-- BEGIN BLOCK: PUBLICKEY -->
<item>
  <label>
 Label: %%%LABEL%%% %%%STATUS%%%
 Key path: %%%PATH%%%</label>
 <!--
   %%%ALGORITHM%%% [hash #%%%HASH%%%]
   File name: %%%FILENAME%%%
 -->
 <value>%%%ID%%%</value>
</item>
<!-- END BLOCK: PUBLICKEY -->

<item><label>Cancel</label><value>cancel</value></item>
<send submission="ok"></send>
</select1>

<submit ref="ok" >
<label>OK</label>
</submit>

</form>

=== olawale24/myserver/opt/tectia/share/auxdata/common/af-passphrase.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE form PUBLIC "ssh-secsh-auth-form-1.dtd" "ssh-secsh-auth-form-1.dtd">
<form id="passphrase">
<label></label>
<!-- BEGIN BLOCK: KEY PATH -->
<label>Key path: %%%VALUE%%%</label>
<!-- END BLOCK: KEY PATH -->
<!-- BEGIN BLOCK: KEY LABEL -->
<label>Key label: %%%VALUE%%%</label>
<!-- END BLOCK: KEY LABEL -->
<!-- BEGIN BLOCK: KEY FILE -->
<label>File name: %%%VALUE%%%</label>
<!-- END BLOCK: KEY FILE -->
<!-- BEGIN BLOCK: TOKEN LABEL -->
<label>Token label: %%%VALUE%%%</label>
<!-- END BLOCK: TOKEN LABEL -->
<!-- BEGIN BLOCK: TOKEN MANUFACTURER -->
<label>Manufacturer: %%%VALUE%%%</label>
<!-- END BLOCK: TOKEN MANUFACTURER -->
<secret ref="passphrase">
<label>Passphrase for the private key</label>
<send submission="ok" />
</secret>
<submit ref="ok" >
<label>OK</label>
</submit>
<submit ref="cancel" >
<label>Cancel</label>
</submit>
</form>

=== olawale24/myserver/opt/tectia/share/auxdata/common/af-hostkeychanged-gui.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE form PUBLIC "ssh-secsh-auth-form-1.dtd" "ssh-secsh-auth-form-1.dtd">
<form id="hostkeychanged">
<label/>
<label>Saved key for the host "%%%SERVERHOST-SERVERPORT%%%" does not match.</label>
<label>
@@
@@ WARNING: SERVER HOST IDENTIFICATION HAS CHANGED!
@@

There are many possible reasons for this:
1. The administrator of the remote host computer has changed the host key.
2. The remote host computer is part of a server cluster.
3. SOMEONE COULD BE EAVESDROPPING ON YOU RIGHT NOW (man-in-the-middle attack)!

It is NOT RECOMMENDED to connect to the remote host computer until you have
contacted the system administrator and found out why the host identification
has changed.
 
The fingerprint of the host public key is:
"%%%HOSTKEYFINGERPRINT%%%"

You can get a public key's fingerprint by running following command
% ssh-keygen-g3 -F publickey.pub
on the key file.  You should check the validity of the host key ASAP.

If you choose to continue the connection without saving the changed
key, the following steps will be taken to ensure your privacy:
  - Agent forwarding is disabled to avoid attacks by corrupted servers.
  - X11 forwarding is disabled to avoid attacks by corrupted servers.
If you are not absolutely sure about what you are doing, choose Cancel
and contact the administrator of the server system.
</label>
<select1 ref="hostkeycheck">
<label>Please select how you want to proceed.</label>
<item>
  <label>Cancel the connection.</label>
  <value>cancel</value>
</item>
<item>
  <label>Proceed with the connection but do not save the new host key.</label>
  <value>once</value>
</item>
<item>
  <label>Proceed with the connection and replace the host key(s) in the database.</label>
  <value>save</value>
</item>
<item>
  <label>Proceed with the connection and add the host key as an alternate identification.</label>
  <value>new</value>
</item>
<value>cancel</value>
</select1>
<submit ref="ok" >
<label>OK</label>
</submit>
</form>
