=== olawale24/myserver/opt/tectia/share/auxdata/ssh-broker-ng/ssh-broker-ng-config-1.dtd
<!--									-->
<!--									-->
<!-- secsh-broker.dtd							-->
<!--									-->
<!-- Copyright (c) 2016 SSH Communications Security Corporation.        -->
<!-- This software is protected by international copyright laws.        -->
<!-- All rights reserved.                                               -->
<!--									-->
<!-- Document type definition for the Connection Broker XML		-->
<!-- configuration files.						-->
<!--									-->
<!--									-->

<!-- Tunable parameters used in the policy. -->

<!-- Both ipv4 and ipv6 are enabled by default -->
<!ENTITY default-address-family-type		"any">

<!-- The top-level element -->
<!ELEMENT secsh-broker	(general?,default-settings?,profiles?,
			 static-tunnels?,gui?,
			 filter-engine?,logging?)>
<!ATTLIST secsh-broker
	  version	CDATA #IMPLIED>

<!-- General element. Only "known-hosts" can appear multiple times. -->
<!ELEMENT general	(crypto-lib|cert-validation|key-stores|
			 strict-host-key-checking|host-key-always-ask|
			 accept-unknown-host-keys|known-hosts|
	                 user-config-directory|file-access-control|
	                 protocol-parameters)*>

<!-- Cryptographic library. -->
<!ELEMENT crypto-lib	EMPTY>
<!ATTLIST crypto-lib
	  mode	(fips|standard) "standard">

<!-- PKI settings. "dod-pki" element may appear only once, other elements -->
<!-- may be specified multiple times. -->

<!ELEMENT cert-validation	(ldap-server|
                                 ocsp-responder|
                                 crl-prefetch|
                                 dod-pki|
				 ca-certificate|
				 key-store)*>

<!ATTLIST cert-validation
	  end-point-identity-check (yes|no|YES|NO|ask|ASK) "yes"
	  default-domain      CDATA   #IMPLIED
	  http-proxy-url      CDATA   #IMPLIED
	  socks-server-url    CDATA   #IMPLIED
	  max-path-length     CDATA   "10"
	  cache-size          CDATA   "300"
	  max-crl-size        CDATA   "50"
	  external-search-timeout  CDATA  "600"
	  max-ldap-response-length CDATA  "50"
	  ldap-idle-timeout   CDATA   "30">

<!ELEMENT ldap-server	EMPTY>
<!ATTLIST ldap-server
	  address	CDATA #REQUIRED
	  port		CDATA "389">

<!ELEMENT ocsp-responder (#PCDATA)>
<!ATTLIST ocsp-responder
	  url		  CDATA #REQUIRED
	  validity-period CDATA "0"
	  responder-certificate CDATA #IMPLIED>

<!-- CRL prefetch. -->
<!ELEMENT crl-prefetch		EMPTY>
<!ATTLIST crl-prefetch
	  interval		CDATA	"3600"
	  url			CDATA	#REQUIRED>

<!-- CA certificates. -->
<!ELEMENT ca-certificate (#PCDATA)>
<!ATTLIST ca-certificate
	  name		CDATA #REQUIRED
	  file		CDATA #IMPLIED
	  disable-crls	(yes|no|YES|NO) "no"
	  use-expired-crls CDATA "0" >

<!-- Enforce digital signature in key usage. -->
<!ELEMENT dod-pki		EMPTY>
<!ATTLIST dod-pki
	  enable	(yes|no|YES|NO) "no" >

<!ELEMENT key-stores ((key-store|user-keys|identification)*)>

<!ELEMENT key-store EMPTY>
<!ATTLIST key-store
	  type		 CDATA #REQUIRED
	  init		 CDATA #IMPLIED
	  disable-crls	(yes|no|YES|NO) "no"
	  use-expired-crls CDATA "0" >

<!ELEMENT user-keys EMPTY>
<!ATTLIST user-keys
          directory               CDATA #IMPLIED
	  poll-interval           CDATA "10"
          passphrase-timeout      CDATA "0"
          passphrase-idle-timeout CDATA "0">

<!ELEMENT identification EMPTY>
<!ATTLIST identification
          file                    CDATA #REQUIRED
          base-path               CDATA #IMPLIED
          passphrase-timeout      CDATA "0"
          passphrase-idle-timeout CDATA "0">

<!-- This element is deprecated and included for backwards compatibility only -->
<!ELEMENT strict-host-key-checking EMPTY>
<!ATTLIST strict-host-key-checking
	  enable (yes|no|YES|NO) #REQUIRED>

<!-- This element is deprecated and included for backwards compatibility only -->
<!ELEMENT host-key-always-ask EMPTY>
<!ATTLIST host-key-always-ask
	  enable (yes|no|YES|NO) #REQUIRED>

<!-- This element is deprecated and included for backwards compatibility only -->
<!ELEMENT accept-unknown-host-keys EMPTY>
<!ATTLIST accept-unknown-host-keys
          enable (yes|no|YES|NO) #REQUIRED>

<!ELEMENT exclusive-connection EMPTY>
<!ATTLIST exclusive-connection
          enable (yes|no|YES|NO) #REQUIRED>

<!ELEMENT known-hosts (key-store*)>
<!ATTLIST known-hosts
	  path		CDATA #IMPLIED
	  file		CDATA #IMPLIED
	  directory	CDATA #IMPLIED
          filename-format	(hash|plain|default) "default" >

<!-- Extended plugin configuration -->
<!ELEMENT extended (ext)*>

<!ELEMENT ext (#PCDATA | EMPTY | ext)*>
<!ATTLIST ext
          name CDATA #REQUIRED>

<!-- Default settings element.  No element may appear multiple times. -->
<!ELEMENT default-settings	(ciphers|macs|kexs|hostkey-algorithms|
				 transport-distribution|rekey|
				 authentication-methods|
				 hostbased-default-domain|
				 compression|proxy|idle-timeout|
                                 tcp-connect-timeout|keepalive-interval|
	                         exclusive-connection|server-banners|
	                         forwards|extended|remote-environment|
				 server-authentication-methods|
				 authentication-success-message|
				 sftpg3-mode|terminal-selection|terminal-bell|
	                         close-window-on-disconnect|quiet-mode|
	                         checksum|address-family)*>

<!ATTLIST default-settings
	  user	CDATA #IMPLIED>

<!-- Server banners. -->
<!ELEMENT server-banners	EMPTY>
<!ATTLIST server-banners
	  visible	(yes|no|YES|NO) "yes">

<!-- Ciphers element. -->
<!ELEMENT ciphers	(cipher*)>

<!-- Cipher. -->
<!ELEMENT cipher	EMPTY>
<!ATTLIST cipher
	  name	CDATA #REQUIRED>

<!-- Macs element. -->
<!ELEMENT macs	(mac*)>

<!-- Mac. -->
<!ELEMENT mac	EMPTY>
<!ATTLIST mac
	  name	CDATA #REQUIRED>

<!-- Kexs element. -->
<!ELEMENT kexs	(kex*)>

<!-- Kex. -->
<!ELEMENT kex	EMPTY>
<!ATTLIST kex
	  name	CDATA #REQUIRED>

<!-- Hostkey algorithms element. -->
<!ELEMENT hostkey-algorithms (hostkey-algorithm*)>

<!-- Hostkey algorithm. -->
<!ELEMENT hostkey-algorithm   EMPTY>
<!ATTLIST hostkey-algorithm
	  name  CDATA #REQUIRED>

<!ELEMENT rekey	  EMPTY>
<!ATTLIST rekey
	  bytes CDATA "0">

<!-- Hostbased default domain. -->
<!ELEMENT hostbased-default-domain EMPTY>
<!ATTLIST hostbased-default-domain
          name  CDATA #REQUIRED>

<!-- Authentication methods element. -->
<!ELEMENT authentication-methods (authentication-method|auth-hostbased
				  |auth-password|auth-publickey|auth-gssapi
				  |auth-keyboard-interactive)*>
<!ELEMENT server-authentication-methods (authentication-method
					 |auth-server-publickey
					 |auth-server-certificate)*>

<!ELEMENT auth-server-publickey	EMPTY>
<!ATTLIST auth-server-publickey
	  policy	CDATA #IMPLIED>  <!-- "strict", "ask", "tofu", -->
                                         <!-- "advisory" -->

<!ELEMENT auth-server-certificate	EMPTY>


<!ELEMENT remote-environment (environment*)>

<!ELEMENT environment EMPTY>
<!ATTLIST environment
          name		CDATA #REQUIRED
	  value         CDATA #REQUIRED
          format	(yes|no|YES|NO) "no">

<!-- This element is deprecated and included for backwards compatibility only -->
<!ELEMENT transport-distribution EMPTY>
<!ATTLIST transport-distribution
	  num-transports	CDATA #REQUIRED>

<!-- This element is deprecated and included for backwards compatibility only -->
<!ELEMENT authentication-method	EMPTY>
<!ATTLIST authentication-method
	  name	CDATA #REQUIRED>

<!ELEMENT auth-hostbased	(local-hostname?)>
<!ELEMENT local-hostname EMPTY>
<!ATTLIST local-hostname
	  name CDATA #REQUIRED>

<!ELEMENT auth-password EMPTY>

<!ELEMENT auth-publickey (key-selection?)>
<!ATTLIST auth-publickey
	  signature-algorithms CDATA #IMPLIED>
<!ELEMENT key-selection (public-key|issuer-name|subject-name|
	                 extended-key-usage|key-usage|policy-info)*>
<!ATTLIST key-selection
	  policy                   CDATA #IMPLIED
	  exclude                  (yes|no|YES|NO) "no"
     	  require-all              (yes|no|YES|NO) "no">
<!ELEMENT public-key EMPTY>
<!ATTLIST public-key
	  type                     CDATA #REQUIRED>
<!ELEMENT issuer-name EMPTY>
<!ATTLIST issuer-name
	  name                     CDATA #IMPLIED
	  pattern                  CDATA #IMPLIED
          match-server-certificate (yes|no|YES|NO) "no">
<!ELEMENT subject-name EMPTY>
<!ATTLIST subject-name
	  name                     CDATA #IMPLIED
	  pattern                  CDATA #IMPLIED>
<!ELEMENT extended-key-usage (#PCDATA)>
<!ATTLIST extended-key-usage
          oid                      CDATA #IMPLIED
          explicit                 (yes|no|YES|NO) "no">
<!ELEMENT key-usage (#PCDATA)>
<!ATTLIST key-usage
          bit                      CDATA #IMPLIED>
<!ELEMENT auth-keyboard-interactive EMPTY>
<!ELEMENT auth-gssapi EMPTY>

<!-- Actually, the default for allow-ticket-forwarding is "no", but we
     don't want to override value if it is left undefined. -->
<!ATTLIST auth-gssapi
	  dll-path		      CDATA   "/usr/lib/libgssapi_krb5.so,/usr/lib64/libgssapi_krb5.so,/usr/lib/libkrb5.so,/usr/lib/libgss.so,/usr/local/gss/gl/mech_krb5.so,/usr/local/lib/libgssapi_krb5.so,/usr/local/lib/libkrb5.so,/usr/kerberos/lib/libgssapi_krb5.so,/usr/kerberos/lib/libkrb5.so,/usr/lib/gss/libgssapi_krb5.so,/usr/kerberos/lib/libgssapi_krb5.so.2,/usr/lib/libgssapi_krb5.so.2,/usr/lib/amd64/gss/mech_krb5.so,/usr/lib/amd64/libgss.so"
	  allow-ticket-forwarding     (yes|no)  #IMPLIED>

<!-- User identities. -->
<!ELEMENT user-identities (identity*)>
<!ELEMENT identity EMPTY>
<!ATTLIST identity
          identity-file CDATA #IMPLIED
          file CDATA #IMPLIED
          hash CDATA #IMPLIED
          id CDATA #IMPLIED
          data  CDATA #IMPLIED>

<!-- Password. -->
<!ELEMENT password (#PCDATA)>
<!ATTLIST password
          string    CDATA #IMPLIED
          file      CDATA #IMPLIED
          command   CDATA #IMPLIED>

<!-- Proxy rules. -->
<!ELEMENT proxy	EMPTY>
<!ATTLIST proxy
	  ruleset	CDATA #REQUIRED>

<!-- Idle timeout. -->
<!ELEMENT idle-timeout	EMPTY>
<!ATTLIST idle-timeout
	  type	(connection) "connection"
	  time	CDATA #IMPLIED>

<!-- Connect timeout. -->
<!ELEMENT tcp-connect-timeout	EMPTY>
<!ATTLIST tcp-connect-timeout
	  time	CDATA #REQUIRED>

<!-- Keepalive interval. -->
<!ELEMENT keepalive-interval	EMPTY>
<!ATTLIST keepalive-interval
	  time	CDATA #REQUIRED>

<!-- Forwards element. -->
<!ELEMENT forwards	(forward*)>

<!-- Forward. -->
<!ELEMENT forward	EMPTY>
<!ATTLIST forward
	  type	(x11|agent)    #REQUIRED
	  state	(on|off|denied) #REQUIRED>


<!-- Compression. -->
<!ELEMENT compression	EMPTY>
<!ATTLIST compression
	  name	CDATA #IMPLIED
	  level CDATA #IMPLIED>

<!ELEMENT authentication-success-message EMPTY>
<!ATTLIST authentication-success-message
	  enable		(yes|no|YES|NO) "yes">

<!ELEMENT quiet-mode EMPTY>
<!ATTLIST quiet-mode
	  enable		(yes|no|YES|NO) "no">

<!ELEMENT sftpg3-mode EMPTY>
<!ATTLIST sftpg3-mode
	  compatibility-mode	CDATA "tectia">

<!ELEMENT terminal-selection EMPTY>
<!ATTLIST terminal-selection
    selection-type (select-words|select-paths) "select-words">

<!ELEMENT terminal-bell EMPTY>
<!ATTLIST terminal-bell
    bell-style (none|pc-speaker|system-default) "system-default">

<!ELEMENT close-window-on-disconnect EMPTY>
<!ATTLIST close-window-on-disconnect
    enable (yes|no) "no">

<!ELEMENT checksum EMPTY>
<!ATTLIST checksum
          type     (yes|no|md5|sha1|md5-force|sha1-force|checkpoint|
                    YES|NO|MD5|SHA1|MD5-FORCE|SHA1-FORCE|CHECKPOINT) "yes">

<!ELEMENT user-config-directory EMPTY>
<!ATTLIST user-config-directory
	  path	CDATA "%USER_CONFIG_DIRECTORY%">

<!ELEMENT file-access-control EMPTY>
<!ATTLIST file-access-control
	  enable (yes|no|YES|NO) "no">

<!-- address-family mode setting ipv4 & ipv6-->
<!ELEMENT address-family	EMPTY>
<!ATTLIST address-family
	  type		(any|inet|inet6) "&default-address-family-type;">

<!ELEMENT protocol-parameters EMPTY>
<!ATTLIST protocol-parameters
	  threads CDATA #IMPLIED>

<!-- Profiles element. -->
<!ELEMENT profiles	(profile*)>

<!-- Connection profile.  No element may appear multiple times. -->
<!ELEMENT profile	(hostkey|ciphers|macs|kexs|hostkey-algorithms|
			 transport-distribution|rekey|
			 authentication-methods|
                         user-identities|
			 compression|proxy|idle-timeout|
                         tcp-connect-timeout|keepalive-interval|
	                 exclusive-connection|server-banners|
	                 forwards|tunnels|extended|remote-environment|
			 server-authentication-methods|password|
                         profile-group)*>
<!ATTLIST profile
	  id	CDATA #IMPLIED
	  name	CDATA #IMPLIED
	  host	CDATA #REQUIRED
	  port	CDATA "22"
          protocol CDATA "secsh2"
	  host-type (unix|windows|default) "default"
	  connect-on-startup (yes|no|YES|NO) "no"
	  user	CDATA #IMPLIED
	  gateway-profile CDATA #IMPLIED>

<!ELEMENT profile-group EMPTY>
<!ATTLIST profile-group
          name  CDATA #REQUIRED>

<!-- Hostkey. -->
<!ELEMENT hostkey	(#PCDATA)>
<!ATTLIST hostkey
	  file	CDATA #IMPLIED>

<!-- Tunnels element. -->
<!ELEMENT tunnels	(local-tunnel*,remote-tunnel*)>

<!-- Local tunnel. -->
<!ELEMENT local-tunnel	EMPTY>
<!ATTLIST local-tunnel
	  type	CDATA "tcp"
	  listen-address	CDATA "127.0.0.1"
	  listen-port	CDATA #REQUIRED
	  dst-host CDATA "127.0.0.1"
	  dst-port CDATA #REQUIRED
	  allow-relay (yes|no|YES|NO) "no">

<!-- Remote tunnel. -->
<!ELEMENT remote-tunnel	EMPTY>
<!ATTLIST remote-tunnel
	  type	CDATA "tcp"
	  listen-address	CDATA "127.0.0.1"
	  listen-port	CDATA #REQUIRED
	  dst-host CDATA "127.0.0.1"
	  dst-port CDATA #REQUIRED
	  allow-relay (yes|no|YES|NO) "no">

<!-- Static tunnels element. -->
<!ELEMENT static-tunnels	(tunnel*)>

<!-- Static tunnel. -->
<!ELEMENT tunnel	EMPTY>
<!ATTLIST tunnel
	  type	CDATA "tcp"
	  listen-address	CDATA "127.0.0.1"
	  listen-port	CDATA #REQUIRED
	  dst-host CDATA "127.0.0.1"
	  dst-port CDATA #REQUIRED
	  allow-relay (yes|no|YES|NO) "no"
	  profile CDATA #REQUIRED>

<!-- GUI. -->
<!ELEMENT gui EMPTY>
<!ATTLIST gui
	  hide-tray-icon		(yes|no|YES|NO) "no"
	  show-exit-button		(yes|no|YES|NO) "yes"
	  show-admin			(yes|no|YES|NO) "yes"
	  enable-connector		(yes|no|YES|NO) "yes"
	  show-security-notification	(yes|no|YES|NO) "yes">

<!ELEMENT filter-engine (network|dns|filter|rule)*>
<!ATTLIST filter-engine
      ip-generate-start   CDATA "198.18.0.1"
      ip6-generate-start  CDATA "2001:db8::ff00:42:8329"
      ftp-filter-at-signs (yes|no|YES|NO) "no">

<!ELEMENT network EMPTY>
<!ATTLIST network
	  id		      ID    #REQUIRED
	  address	      CDATA #IMPLIED
	  domain	      CDATA #IMPLIED
	  ip-generate-start   CDATA #IMPLIED
	  ip6-generate-start   CDATA #IMPLIED>

<!ELEMENT dns EMPTY>
<!ATTLIST dns
	  id		      ID    #REQUIRED
	  network-id	      IDREF #IMPLIED
	  application	      CDATA #IMPLIED
	  host		          CDATA #IMPLIED
	  ip-address	      CDATA #IMPLIED
	  pseudo-ip (yes|no|YES|NO) "no">

<!ELEMENT filter EMPTY>
<!ATTLIST filter
	  dns-id	      IDREF #REQUIRED
	  ports		      CDATA #REQUIRED
	  action	       (block|direct|tunnel|ftp-tunnel|ftp-proxy|
                                BLOCK|DIRECT|TUNNEL|FTP-TUNNEL|FTP-PROXY)
                              #REQUIRED
	  profile-id	      CDATA #IMPLIED
    destination         CDATA #IMPLIED
    destination-port    CDATA #IMPLIED
	  fallback-to-plain (yes|no|YES|NO) "no">

<!ELEMENT rule EMPTY>
<!ATTLIST rule
	  application	      	CDATA #IMPLIED
	  host		      			CDATA #IMPLIED
	  ip-address	      	CDATA #IMPLIED
	  pseudo-ip 					(yes|no|YES|NO) "no"
	  ports		      			CDATA #REQUIRED
	  action	            (block|direct|tunnel|ftp-tunnel|ftp-proxy|
                         BLOCK|DIRECT|TUNNEL|FTP-TUNNEL|FTP-PROXY)
                              #REQUIRED
	  profile-id	      	CDATA #IMPLIED
    destination         CDATA #IMPLIED
    destination-port    CDATA #IMPLIED
    username            CDATA #IMPLIED
    hostname-from-app   (yes|no|YES|NO) "no"
    username-from-app   (yes|no|YES|NO) "no"
	  fallback-to-plain 	(yes|no|YES|NO) "no"
    show-sftp-server-banner    (yes|no|YES|NO) "no">



<!ELEMENT logging	(log-target*,log-events*)>

<!-- Log events. -->
<!-- Log event facility. -->
<!ENTITY default-log-event-facility		  "normal">

<!-- Log event severity. -->
<!ENTITY default-log-event-severity		  "notice">

<!ELEMENT log-target	EMPTY>
<!ATTLIST log-target
	  file		CDATA			#IMPLIED
	  type		(file|syslog|socket|discard) 	"file"
	  format	(syslog|csv|xml)        "syslog" >

<!ELEMENT log-events	(log-target|#PCDATA)*>
<!ATTLIST log-events
	  facility	(normal|daemon|user|auth|local0|local1|
			local2|local3|local4|local5|local6|local7|discard)
			"&default-log-event-facility;"
	  severity	(informational|notice|warning|error|critical|
			security-success|security-failure)
			"&default-log-event-severity;">

=== olawale24/myserver/etc/ssh2/ssh-broker-config-example.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE secsh-broker SYSTEM "ssh-broker-ng-config-1.dtd" >

<!-- Tectia Connection Broker - ssh-broker-config-example.xml

     NOTE: This file contains an example configuration for ssh-broker-g3.
     Consider this file only as an example and create a real configuration 
     to suit your environment.
     
     To use this file as a basis of your Connection Broker configuration,
     copy it under name "ssh-broker-config.xml" to your user-specific directory
     on Unix: $HOME/.ssh2/ssh-broker-config.xml
     on Windows: %APPDATA%\SSH\ssh-broker-config.xml

     Edit the file using a text editor or an XML editor. For more 
     information on the configuration syntax, see the ssh-broker-config
     manual page or documentation:
     Tectia Client User Manual or 
     Tectia ConnectSecure Administrator Manual.

     The Connection Broker locates the DTD automatically. 
-->

<secsh-broker version="6.4">
  <general>
    <!-- By default, the crypto libraries are used in the "standard" mode.
         They can also be used in the "fips" mode. -->
    <crypto-lib mode="standard" />


    <!-- Example of certificate validation settings -->
<!--
    <cert-validation end-point-identity-check="yes"
                     default-domain="example.com"
                     http-proxy-url="http://proxy.example.com:8080"
		     max-path-length="12"
		     cache-size="35"
		     max-crl-size="11"
		     external-search-timeout="60"
		     max-ldap-response-length="11"
		     ldap-idle-timeout="30">
      <ldap-server address="ldap://ldap.example.com:389" />
      <ocsp-responder url="http://ocsp.example.com:8090" validity-period="0" /> 
      <crl-prefetch interval="3600" url="file:///full.path.to.crlfile" />
      <dod-pki enable="no" />
      <ca-certificate name="SSH Test CA1"
                      file="ssh_test_ca1.crt"
                      disable-crls="no"
                      use-expired-crls="0" />
    </cert-validation>         
-->
  </general>

  <!-- Default connection settings -->
  <default-settings>
    <ciphers>
      <cipher name="crypticore128@ssh.com" /> <!-- on Windows and Linux x86--> 
      <cipher name="aes128-cbc" />
      <cipher name="aes192-cbc" />
      <cipher name="aes256-cbc" />
      <cipher name="aes128-ctr" />
      <cipher name="aes192-ctr" />
      <cipher name="aes256-ctr" />
      <cipher name="3des-cbc" />
    </ciphers>

    <macs>
      <mac name="crypticore-mac@ssh.com" /> <!-- on Windows and Linux x86--> 
      <mac name="hmac-sha1" />
      <mac name="hmac-sha1-96" />
      <mac name="hmac-sha2-256" />
      <mac name="hmac-sha256-2@ssh.com" />
      <mac name="hmac-sha224@ssh.com" />
      <mac name="hmac-sha256@ssh.com" />
      <mac name="hmac-sha384@ssh.com" />
      <mac name="hmac-sha2-512" />
      <mac name="hmac-sha512@ssh.com" />
    </macs>
    
    <kexs>
      <kex name="diffie-hellman-group14-sha1" />
      <kex name="diffie-hellman-group14-sha256@ssh.com" />
      <kex name="diffie-hellman-group-exchange-sha1" />
      <kex name="diffie-hellman-group-exchange-sha256" />
    </kexs>

    <rekey bytes="1000000000" />

    <authentication-methods>
      <auth-publickey />
      <auth-password />
      <auth-keyboard-interactive />
    </authentication-methods>

    <compression name="none"
                 level="0"/>

    <!-- Default proxy rules -->
<!--
    <proxy ruleset="direct:///10.0.0.0/8,127.0.0.0/8,*.example.com;socks://fw.example.com:1080/" />
-->

    <idle-timeout type="connection" time="5" />

    <server-banners visible="yes" />

    <forwards>
      <forward type="x11" state="off" />
      <forward type="agent" state="on" />
    </forwards>

    <!-- By default, the address family is any.
         It also can be inet (IPv4) or inet6 (IPv6). -->
    <address-family type="any" />

  </default-settings>

  <!-- Connection profiles and profile-specific settings -->
  <profiles>
    <!-- Example profile 1 -->
    <profile name="server1"
             id="id1"
             host="server1.example.com"
             port="22"
             connect-on-startup="NO"
             user="%username%"
             gateway-profile="">
      <hostkey>
      </hostkey>

      <ciphers>
        <cipher name="crypticore128@ssh.com" />
        <cipher name="aes128-cbc" />
        <cipher name="3des-cbc" />
        <cipher name="twofish128-cbc" />
      </ciphers>

      <macs>
        <mac name="crypticore-mac@ssh.com" />
        <mac name="hmac-sha1" />
        <mac name="hmac-md5" />
      </macs>

      <authentication-methods>
        <auth-publickey/>
        <auth-password />
      </authentication-methods>

      <compression name="none"
                   level="0"/>

      <!-- Profile-specific proxy rules --> 
<!--
      <proxy ruleset="" />
-->

      <idle-timeout type="connection" time="5" />

      <server-banners visible="no" />

      <forwards>
        <forward type="agent" state="on" />
        <forward type="x11" state="on" />
      </forwards>

      <tunnels>
        <local-tunnel type="TCP" 
                      listen-port="143"
                      dst-host="imap.example.com"
                      dst-port="143"
                      allow-relay="NO" />
        <remote-tunnel type="TCP"
                       listen-port="11000"
                       dst-host="localhost"
                       dst-port="99" />
      </tunnels>

    </profile>

    <!-- Example profile 2 -->
    <profile name="server2"
             id="id2"
             host="server2.example.com"
             port="22"
             connect-on-startup="NO"
             user="%username%"
             gateway-profile="">
      <hostkey>
      </hostkey>

      <compression name="none" />

      <proxy ruleset="" />
    </profile>
  </profiles>

  <!-- Automatic tunnels -->  
  <static-tunnels>
    <tunnel listen-port="25"
            dst-host="smtp.example.com"
            dst-port="25"
            allow-relay="NO"
            type="TCP"
            profile="id1" />
  </static-tunnels>
  
  <!-- Windows GUI settings -->
  <gui hide-tray-icon="no"
       show-exit-button="yes"
       show-admin="yes"
       enable-connector="yes"
       show-security-notification="yes" />

  <!-- Filter rules for ConnectSecure
       * transparent TCP tunneling 
       * transparent FTP tunneling 
       * FTP-SFTP conversion 
       
       Example rule tunnels all port 23 (telnet) connections 
       via the Secure Shell server defined in profile "id1".
-->
<!-- 
  <filter-engine ip-generate-start = "198.18.0.1">

    <rule application=".*"
          host=".*"
          ip-address=".*"
          pseudo-ip="no"
          ports="23"
          action="TUNNEL"
          profile-id="id1"
          hostname-from-app="no"
          username-from-app="no"
          fallback-to-plain="no" />

  </filter-engine>
-->

  <!-- Customized logging settings -->
<!--
  <logging>
    <log-events facility="normal"
                severity="informational">Broker_channel_control
					 Broker_channel_close
    </log-events>
  </logging>
-->

</secsh-broker>

=== olawale24/myserver/opt/tectia/share/auxdata/ssh-broker-ng/ssh-broker-config-default.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE secsh-broker SYSTEM "ssh-broker-ng-config-1.dtd">
<!-- WARNING! This file contains the factory defaults     -->
<!-- for the Connection Broker and is read-only.          -->
<!-- Any changes to this file will be lost on upgrade.    -->
<secsh-broker version = "1.0" >

  <default-settings>
    <ciphers>
      <cipher name="crypticore128@ssh.com" />
      <cipher name="aes128-cbc" />
      <cipher name="aes128-ctr" />
      <cipher name="aes192-cbc" />
      <cipher name="aes192-ctr" />
      <cipher name="aes256-cbc" />
      <cipher name="aes256-ctr" />
      <cipher name="3des-cbc" />
    </ciphers>

    <macs>
      <mac name="crypticore-mac@ssh.com" />
      <mac name="hmac-sha1" />
      <mac name="hmac-sha1-96" />
      <mac name="hmac-sha2-256" />
      <mac name="hmac-sha256-2@ssh.com" />
      <mac name="hmac-sha224@ssh.com" />
      <!-- Backwards compatible to 4.x (uses 16-byte key). -->
      <mac name="hmac-sha256@ssh.com" />
      <mac name="hmac-sha384@ssh.com" />
      <mac name="hmac-sha2-512" />
      <mac name="hmac-sha512@ssh.com" />
    </macs>

    <kexs>
      <kex name="diffie-hellman-group14-sha1" />
      <kex name="diffie-hellman-group14-sha256@ssh.com" />
      <kex name="diffie-hellman-group-exchange-sha1" />
      <kex name="diffie-hellman-group-exchange-sha256" />      
    </kexs>

    <hostkey-algorithms>
      <hostkey-algorithm name="ssh-dss" />
      <hostkey-algorithm name="ssh-rsa" />
      <hostkey-algorithm name="ssh-dss-sha256@ssh.com" />
      <hostkey-algorithm name="ssh-rsa-sha256@ssh.com" />
      <hostkey-algorithm name="x509v3-sign-dss" />
      <hostkey-algorithm name="x509v3-sign-rsa" />
      <hostkey-algorithm name="x509v3-sign-dss-sha256@ssh.com" />
      <hostkey-algorithm name="x509v3-sign-rsa-sha256@ssh.com" />      
    </hostkey-algorithms>

    <rekey bytes="1000000000" />

    <authentication-methods>
      <authentication-method name="publickey" />
      <authentication-method name="password" />
      <authentication-method name="keyboard-interactive" />
      <auth-gssapi />
    </authentication-methods>

    <idle-timeout type="connection" time="5" />

    <server-banners visible="yes" />

    <forwards>
      <forward type="x11" state="off" />
      <forward type="agent" state="on" />
    </forwards>
    
    <authentication-success-message enable="yes"/>
    <quiet-mode enable="no"/> 
    <sftpg3-mode compatibility-mode="tectia"/>
  </default-settings>

  <gui hide-tray-icon="no"
       show-exit-button="yes"
       show-admin="yes"
       enable-connector="yes"
       show-security-notification="yes" />

</secsh-broker>

=== olawale24/myserver/opt/tectia/share/auxdata/ssh-broker-ng/ssh-socks-proxy-config-default.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE secsh-broker SYSTEM "ssh-broker-ng-config-1.dtd">
<!-- WARNING! This file contains the factory defaults     -->
<!-- for the Connection Broker and is read-only.          -->
<!-- Any changes to this file will be lost on upgrade.    -->
<secsh-broker version = "1.0" >

  <default-settings>
    <ciphers>
      <cipher name="crypticore128@ssh.com" />
      <cipher name="aes128-cbc" />
      <cipher name="aes192-cbc" />
      <cipher name="aes256-cbc" />
      <cipher name="aes128-ctr" />
      <cipher name="aes192-ctr" />
      <cipher name="aes256-ctr" />
      <cipher name="3des-cbc" />
      <cipher name="seed-cbc@ssh.com" />
    </ciphers>

    <macs>
      <mac name="crypticore-mac@ssh.com" />
      <mac name="hmac-md5" />
      <mac name="hmac-sha1" />
    </macs>

    <kexs>
      <kex name="diffie-hellman-group-exchange-sha256" />
      <kex name="diffie-hellman-group-exchange-sha1" />
      <kex name="diffie-hellman-group14-sha1" />
    </kexs>

    <transport-distribution num-transports="1" />

    <rekey bytes="1000000000" />

    <authentication-methods>
      <authentication-method name="publickey" />
      <authentication-method name="password" />
      <authentication-method name="keyboard-interactive" />
    </authentication-methods>

    <idle-timeout type="connection" time="5" />

    <server-banners visible="yes" />

    <forwards>
      <forward type="x11" state="off" />
      <forward type="agent" state="on" />
    </forwards>
  </default-settings>

  <gui hide-tray-icon="no"
       show-exit-button="yes"
       show-admin="yes"
       enable-connector="yes"
       show-security-notification="yes" />

</secsh-broker>
